language: python

sudo: false

python:
  - "pypy"
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - TEST_WITH_REDIS= DJANGO_VERSION=">=1.8.0,<1.9.0"
  - TEST_WITH_REDIS=1 DJANGO_VERSION=">=1.8.0,<1.9.0"
  - TEST_WITH_REDIS= DJANGO_VERSION=">=1.9.0,<1.10.0"
  - TEST_WITH_REDIS=1 DJANGO_VERSION=">=1.9.0,<1.10.0"

install:
  - pip install -r requirements.txt
  - pip install Django$DJANGO_VERSION flake8 codecov

matrix:
  exclude:
    - python: "3.8"
      env: DJANGO_VERSION=">=1.9.0,<1.10.0"

script:
  - coverage run --branch runtests.py

after_success:
  - flake8 queued_once setup.py
  - codecov

services:
  - redis-server
