language: python

sudo: false

env:
  - TEST_WITH_REDIS=
  - TEST_WITH_REDIS=1

python:
  - "pypy"
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - pip install flake8 codecov

script:
  - coverage run --branch runtests.py

after_success:
  - flake8 queued_once setup.py
  - codecov

services:
  - redis-server
